### ISSUE TITLE
DevTools 无法加载源映射

### ISSUE THREAD

**Issue by gaoyusongcn** [honghuangdc/vite-ionic-vue#1]
老哥，出现这个问题我是哪里搞错了。

最近在学 `ionic` 然后搜到你这个配置（我自己手动对着你的例子改的） 

出现：

`DevTools 无法加载源映射： 无法加载http://127.0.0.1:5173/tabs/float-elements.css.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE`

![image](https://user-images.githubusercontent.com/43459833/185808718-cb5e83a2-8405-4a84-b9c6-59863256d64d.png)

**Comment by gaoyusongcn** [comment]
少了个配置 [css-devsourcemap](https://cn.vitejs.dev/config/shared-options.html#css-devsourcemap)

**Comment by honghuangdc** [comment]
这个很久没更新了。你可以参考下：https://github.com/honghuangdc/vue3-capacitor-app
